"""Update models to match physical diagram

Revision ID: 0be17b2210d3
Revises: 9c92ec631b05
Create Date: 2026-05-13 13:28:35.608293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0be17b2210d3'
down_revision: Union[str, Sequence[str], None] = '9c92ec631b05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favorites_id'), 'favorites', ['id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('login_at', sa.DateTime(), nullable=False),
    sa.Column('logout_at', sa.DateTime(), nullable=True),
    sa.Column('time_in_the_system', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.drop_index(op.f('ix_owner_contacts_id'), table_name='owner_contacts')
    op.drop_table('owner_contacts')
    op.drop_index(op.f('ix_owners_id'), table_name='owners')
    op.drop_table('owners')
    op.add_column('lead_actions', sa.Column('action_type', sa.Enum('ADD_FAVORITE', 'DELETE_FAVORITE', 'CALL', 'DOWNLOAD_PHOTOS', 'GO_LINK', name='actiontype'), nullable=False))
    op.add_column('lead_actions', sa.Column('action_date', sa.DateTime(), nullable=False))
    op.drop_column('lead_actions', 'is_favorite')
    op.drop_column('lead_actions', 'last_action_time')
    op.alter_column('leads', 'external_url',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('leads', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('leads', 'area',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.drop_constraint(op.f('leads_owner_id_fkey'), 'leads', type_='foreignkey')
    op.drop_column('leads', 'owner_id')
    op.drop_column('leads', 'notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('leads', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('leads_owner_id_fkey'), 'leads', 'owners', ['owner_id'], ['id'])
    op.alter_column('leads', 'area',
               existing_type=sa.Numeric(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('leads', 'price',
               existing_type=sa.Numeric(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('leads', 'external_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.add_column('lead_actions', sa.Column('last_action_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('lead_actions', sa.Column('is_favorite', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('lead_actions', 'action_date')
    op.drop_column('lead_actions', 'action_type')
    op.create_table('owners',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fullname', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('owners_pkey'))
    )
    op.create_index(op.f('ix_owners_id'), 'owners', ['id'], unique=False)
    op.create_table('owner_contacts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('contact_type', postgresql.ENUM('EMAIL', 'PHONE_NUMBER', name='contacttype'), autoincrement=False, nullable=False),
    sa.Column('contact', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], name=op.f('owner_contacts_owner_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('owner_contacts_pkey')),
    sa.UniqueConstraint('contact', name=op.f('owner_contacts_contact_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('owner_id', 'contact', name=op.f('uq_owner_contact'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_owner_contacts_id'), 'owner_contacts', ['id'], unique=False)
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_favorites_id'), table_name='favorites')
    op.drop_table('favorites')
    # ### end Alembic commands ###
