"""add_lead_parser_fields

Revision ID: aa7d115bf03c
Revises: e5edb7be8cf2
Create Date: 2026-02-23 22:10:24.795150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa7d115bf03c'
down_revision: Union[str, Sequence[str], None] = 'e5edb7be8cf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('external_id', sa.String(), nullable=False))
    op.add_column('leads', sa.Column('external_url', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('floors_count', sa.Integer(), nullable=False))
    op.add_column('leads', sa.Column('created_offer_at', sa.DateTime(), nullable=False))
    op.add_column('leads', sa.Column('published_offer_at', sa.DateTime(), nullable=True))
    op.add_column('leads', sa.Column('is_early_access', sa.Boolean(), nullable=False))
    op.add_column('leads', sa.Column('phone_reveal_at', sa.DateTime(), nullable=True))
    op.drop_column('leads', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('leads', 'phone_reveal_at')
    op.drop_column('leads', 'is_early_access')
    op.drop_column('leads', 'published_offer_at')
    op.drop_column('leads', 'created_offer_at')
    op.drop_column('leads', 'floors_count')
    op.drop_column('leads', 'external_url')
    op.drop_column('leads', 'external_id')
    # ### end Alembic commands ###
