"""add source and photo_urls to leads

Revision ID: b47a36c77038
Revises: aa7d115bf03c
Create Date: 2026-04-09 19:56:35.461998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b47a36c77038'
down_revision: Union[str, Sequence[str], None] = 'aa7d115bf03c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('source', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('photo_urls', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'photo_urls')
    op.drop_column('leads', 'source')
    # ### end Alembic commands ###
