"""Remove is_favorite

Revision ID: ba904f024377
Revises: 0be17b2210d3
Create Date: 2026-05-15 11:21:16.312182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba904f024377'
down_revision: Union[str, Sequence[str], None] = '0be17b2210d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorites', 'is_favorite')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('is_favorite', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
